# Pandas

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv(r"C:\Users\hp\Desktop\liver.csv")
df

     Age  Gender    TB   DB  Alkphos  Sgpt  Sgot   TP  ALB    AG  LiverPatient
0     65  Female   0.7  0.1      187    16    18  6.8  3.3  0.90             1
1     62    Male  10.9  5.5      699    64   100  7.5  3.2  0.74             1
2     62    Male   7.3  4.1      490    60    68  7.0  3.3  0.89             1
3     58    Male   1.0  0.4      182    14    20  6.8  3.4  1.00             1
4     72    Male   3.9  2.0      195    27    59  7.3  2.4  0.40             1
..   ...     ...   ...  ...      ...   ...   ...  ...  ...   ...           ...
578   60    Male   0.5  0.1      500    20    34  5.9  1.6  0.37             0
579   40    Male   0.6  0.1       98    35    31  6.0  3.2  1.10             1
580   52    Male   0.8  0.2      245    48    49  6.4  3.2  1.00             1
581   31    Male   1.3  0.5      184    29    32  6.8  3.4  1.00             1
582   38    Male   1.0  0.3      216    21    24  7.3  4.4  1.50             0

[583 rows x 11 columns]

In [3]:
df.shape

(583, 11)

In [4]:
df.size

6413

In [7]:
df.info

<bound method DataFrame.info of      Age  Gender    TB   DB  Alkphos  Sgpt  Sgot   TP  ALB    AG  LiverPatient
0     65  Female   0.7  0.1      187    16    18  6.8  3.3  0.90             1
1     62    Male  10.9  5.5      699    64   100  7.5  3.2  0.74             1
2     62    Male   7.3  4.1      490    60    68  7.0  3.3  0.89             1
3     58    Male   1.0  0.4      182    14    20  6.8  3.4  1.00             1
4     72    Male   3.9  2.0      195    27    59  7.3  2.4  0.40             1
..   ...     ...   ...  ...      ...   ...   ...  ...  ...   ...           ...
578   60    Male   0.5  0.1      500    20    34  5.9  1.6  0.37             0
579   40    Male   0.6  0.1       98    35    31  6.0  3.2  1.10             1
580   52    Male   0.8  0.2      245    48    49  6.4  3.2  1.00             1
581   31    Male   1.3  0.5      184    29    32  6.8  3.4  1.00             1
582   38    Male   1.0  0.3      216    21    24  7.3  4.4  1.50             0

[583 rows x 11 columns]>

In [8]:
df.head()

   Age  Gender    TB   DB  Alkphos  Sgpt  Sgot   TP  ALB    AG  LiverPatient
0   65  Female   0.7  0.1      187    16    18  6.8  3.3  0.90             1
1   62    Male  10.9  5.5      699    64   100  7.5  3.2  0.74             1
2   62    Male   7.3  4.1      490    60    68  7.0  3.3  0.89             1
3   58    Male   1.0  0.4      182    14    20  6.8  3.4  1.00             1
4   72    Male   3.9  2.0      195    27    59  7.3  2.4  0.40             1

In [9]:
df.head(15)

    Age  Gender    TB   DB  Alkphos  Sgpt  Sgot   TP  ALB    AG  LiverPatient
0    65  Female   0.7  0.1      187    16    18  6.8  3.3  0.90             1
1    62    Male  10.9  5.5      699    64   100  7.5  3.2  0.74             1
2    62    Male   7.3  4.1      490    60    68  7.0  3.3  0.89             1
3    58    Male   1.0  0.4      182    14    20  6.8  3.4  1.00             1
4    72    Male   3.9  2.0      195    27    59  7.3  2.4  0.40             1
5    46    Male   1.8  0.7      208    19    14  7.6  4.4  1.30             1
6    26  Female   0.9  0.2      154    16    12  7.0  3.5  1.00             1
7    29  Female   0.9  0.3      202    14    11  6.7  3.6  1.10             1
8    17    Male   0.9  0.3      202    22    19  7.4  4.1  1.20             0
9    55    Male   0.7  0.2      290    53    58  6.8  3.4  1.00             1
10   57    Male   0.6  0.1      210    51    59  5.9  2.7  0.80             1
11   72    Male   2.7  1.3      260    31    56  7.4  3.0  0.60             1
12   64    Male   0.9  0.3      310    61    58  7.0  3.4  0.90             0
13   74  Female   1.1  0.4      214    22    30  8.1  4.1  1.00             1
14   61    Male   0.7  0.2      145    53    41  5.8  2.7  0.87             1

In [11]:
df.tail()

     Age Gender   TB   DB  Alkphos  Sgpt  Sgot   TP  ALB    AG  LiverPatient
578   60   Male  0.5  0.1      500    20    34  5.9  1.6  0.37             0
579   40   Male  0.6  0.1       98    35    31  6.0  3.2  1.10             1
580   52   Male  0.8  0.2      245    48    49  6.4  3.2  1.00             1
581   31   Male  1.3  0.5      184    29    32  6.8  3.4  1.00             1
582   38   Male  1.0  0.3      216    21    24  7.3  4.4  1.50             0

In [12]:
df.tail(15)

,Age,Gender,TB,DB,Alkphos,Sgpt,Sgot,TP,ALB,AG,LiverPatient
568,20,Female,16.7,8.4,200,91,101,6.9,3.5,1.02,1
569,16,Male,7.7,4.1,268,213,168,7.1,4.0,1.20,1
570,16,Male,2.6,1.2,236,131,90,5.4,2.6,0.90,1
571,90,Male,1.1,0.3,215,46,134,6.9,3.0,0.70,1
572,32,Male,15.6,9.5,134,54,125,5.6,4.0,2.50,1
573,32,Male,3.7,1.6,612,50,88,6.2,1.9,0.40,1
574,32,Male,12.1,6.0,515,48,92,6.6,2.4,0.50,1
575,32,Male,25.0,13.7,560,41,88,7.9,2.5,2.50,1
576,32,Male,15.0,8.2,289,58,80,5.3,2.2,0.70,1
577,32,Male,12.7,8.4,190,28,47,5.4,2.6,0.90,1
578,60,Male,0.5,0.1,500,20,34,5.9,1.6,0.37,0
579,40,Male,0.6,0.1,98,35,31,6.0,3.2,1.10,1
580,52,Male,0.8,0.2,245,48,49,6.4,3.2,1.00,1
581,31,Male,1.3,0.5,184,29,32,6.8,3.4,1.00,1
582,38,Male,1.0,0.3,216,21,24,7.3,4.4,1.50,0

In [14]:
df=pd.read_csv(r"C:\Users\hp\Desktop\DemographicData.csv")
df

,Country Name,Country Code,Birth rate,Internet users,Income Group
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [22]:
df["Country Name"]

0                     Aruba
1               Afghanistan
2                    Angola
3                   Albania
4      United Arab Emirates
               ...
190             Yemen, Rep.
191            South Africa
192        Congo, Dem. Rep.
193                  Zambia
194                Zimbabwe
Name: Country Name, Length: 195, dtype: object

In [23]:
df["Country Code"]

0      ABW
1      AFG
2      AGO
3      ALB
4      ARE
      ...
190    YEM
191    ZAF
192    COD
193    ZMB
194    ZWE
Name: Country Code, Length: 195, dtype: object

In [24]:
df.info

<bound method DataFrame.info of              Country Name Country Code  Birth rate  Internet users  \
0                   Aruba          ABW      10.244            78.9
1             Afghanistan          AFG      35.253             5.9
2                  Angola          AGO      45.985            19.1
3                 Albania          ALB      12.877            57.2
4    United Arab Emirates          ARE      11.044            88.0
..                    ...          ...         ...             ...
190           Yemen, Rep.          YEM      32.947            20.0
191          South Africa          ZAF      20.850            46.5
192      Congo, Dem. Rep.          COD      42.394             2.2
193                Zambia          ZMB      40.471            15.4
194              Zimbabwe          ZWE      35.715            18.5

            Income Group
0            High income
1             Low income
2    Upper middle income
3    Upper middle income
4            High income
..                   ...
190  Lower middle income
191  Upper middle income
192           Low income
193  Lower middle income
194           Low income

[195 rows x 5 columns]>

In [25]:
a = ['Apple',2]
s = pd.Series(a)
print(s)
print(type(s))

0    Apple
1        2
dtype: object
<class 'pandas.core.series.Series'>

In [26]:
a = ['Apple',2]
s = pd.Series(a,index = ['b','d'])
print(s)
print(type(s))

b    Apple
d        2
dtype: object
<class 'pandas.core.series.Series'>

In [31]:
import pandas as pd
import numpy as np
df=pd.read_csv(r"C:\Users\hp\Desktop\RTRP\Data sets\liver.csv")
df

     Age  Gender    TB   DB  Alkphos  Sgpt  Sgot   TP  ALB    AG  LiverPatient
0     65  Female   0.7  0.1      187    16    18  6.8  3.3  0.90             1
1     62    Male  10.9  5.5      699    64   100  7.5  3.2  0.74             1
2     62    Male   7.3  4.1      490    60    68  7.0  3.3  0.89             1
3     58    Male   1.0  0.4      182    14    20  6.8  3.4  1.00             1
4     72    Male   3.9  2.0      195    27    59  7.3  2.4  0.40             1
..   ...     ...   ...  ...      ...   ...   ...  ...  ...   ...           ...
578   60    Male   0.5  0.1      500    20    34  5.9  1.6  0.37             0
579   40    Male   0.6  0.1       98    35    31  6.0  3.2  1.10             1
580   52    Male   0.8  0.2      245    48    49  6.4  3.2  1.00             1
581   31    Male   1.3  0.5      184    29    32  6.8  3.4  1.00             1
582   38    Male   1.0  0.3      216    21    24  7.3  4.4  1.50             0

[583 rows x 11 columns]

In [32]:
df.dtypes

Age               int64
Gender           object
TB              float64
DB              float64
Alkphos           int64
Sgpt              int64
Sgot              int64
TP              float64
ALB             float64
AG              float64
LiverPatient      int64
dtype: object

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 583 entries, 0 to 582
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Age           583 non-null    int64
 1   Gender        583 non-null    object
 2   TB            583 non-null    float64
 3   DB            583 non-null    float64
 4   Alkphos       583 non-null    int64
 5   Sgpt          583 non-null    int64
 6   Sgot          583 non-null    int64
 7   TP            583 non-null    float64
 8   ALB           583 non-null    float64
 9   AG            579 non-null    float64
 10  LiverPatient  583 non-null    int64
dtypes: float64(5), int64(5), object(1)
memory usage: 50.2+ KB

In [37]:
df.head()

   Age  Gender    TB   DB  Alkphos  Sgpt  Sgot   TP  ALB    AG  LiverPatient
0   65  Female   0.7  0.1      187    16    18  6.8  3.3  0.90             1
1   62    Male  10.9  5.5      699    64   100  7.5  3.2  0.74             1
2   62    Male   7.3  4.1      490    60    68  7.0  3.3  0.89             1
3   58    Male   1.0  0.4      182    14    20  6.8  3.4  1.00             1
4   72    Male   3.9  2.0      195    27    59  7.3  2.4  0.40             1

In [38]:
df.tail(10)

     Age Gender    TB    DB  Alkphos  Sgpt  Sgot   TP  ALB    AG  LiverPatient
573   32   Male   3.7   1.6      612    50    88  6.2  1.9  0.40             1
574   32   Male  12.1   6.0      515    48    92  6.6  2.4  0.50             1
575   32   Male  25.0  13.7      560    41    88  7.9  2.5  2.50             1
576   32   Male  15.0   8.2      289    58    80  5.3  2.2  0.70             1
577   32   Male  12.7   8.4      190    28    47  5.4  2.6  0.90             1
578   60   Male   0.5   0.1      500    20    34  5.9  1.6  0.37             0
579   40   Male   0.6   0.1       98    35    31  6.0  3.2  1.10             1
580   52   Male   0.8   0.2      245    48    49  6.4  3.2  1.00             1
581   31   Male   1.3   0.5      184    29    32  6.8  3.4  1.00             1
582   38   Male   1.0   0.3      216    21    24  7.3  4.4  1.50             0

In [39]:
df.iloc[580]

Age               52
Gender          Male
TB               0.8
DB               0.2
Alkphos          245
Sgpt              48
Sgot              49
TP               6.4
ALB              3.2
AG               1.0
LiverPatient       1
Name: 580, dtype: object

In [40]:
df.loc[:,'Age']

0      65
1      62
2      62
3      58
4      72
       ..
578    60
579    40
580    52
581    31
582    38
Name: Age, Length: 583, dtype: int64

In [41]:
df.iloc[[3,5]]

   Age Gender   TB   DB  Alkphos  Sgpt  Sgot   TP  ALB   AG  LiverPatient
3   58   Male  1.0  0.4      182    14    20  6.8  3.4  1.0             1
5   46   Male  1.8  0.7      208    19    14  7.6  4.4  1.3             1

In [43]:
df['TB'].values

array([ 0.7, 10.9,  7.3,  1. ,  3.9,  1.8,  0.9,  0.9,  0.9,  0.7,  0.6,
        2.7,  0.9,  1.1,  0.7,  0.6,  1.8,  1.6,  0.9,  0.9,  2.2,  2.9,
        6.8,  1.9,  0.9,  4.1,  4.1,  6.2,  1.1,  0.7,  4. ,  0.9,  1. ,
        2.6,  2.6,  1.3,  0.7, 14.2,  1.4,  2.7,  2.4,  0.6,  6.8,  2.6,
        1. ,  1.8,  3.9,  1.1,  0.6, 18.4,  0.7,  0.6,  3.1,  1.1,  8.9,
        8.9,  0.8,  0.9,  0.8,  1.1,  0.8,  1. ,  1. ,  0.7,  1.3,  1.4,
        2.2,  1.8,  0.7,  0.8,  0.7,  0.8,  0.8,  0.6,  0.7,  0.7,  0.9,
        0.6,  1.4,  2.8,  2.4,  1. ,  0.7,  2. ,  0.6,  1.4,  0.6,  0.8,
        0.6,  4. ,  5.7,  6.8,  8.6,  5.8,  5.2,  0.9,  3.8,  6.6,  0.6,
        0.7,  0.6,  0.7,  0.9,  0.8,  0.5,  5.3,  5.3,  0.8,  0.8,  0.9,
        0.7,  3.2,  1.2,  0.6,  5.8,  7.3,  0.7, 12.7, 15.9, 18. , 23. ,
       22.7,  1.7,  0.8,  0.6,  1.8,  5.8,  3. ,  1.7,  2.8,  3.2,  0.7,
        0.8,  0.9,  1.8, 11.3,  4.7,  0.8,  0.8,  0.8,  0.6,  4.2,  1.6,
        1.6,  3.5,  0.8,  2.9,  0.7,  0.9,  0.8,  1.1,  1.6,  0.8,  0.6,
        5.9,  8.7,  0.9,  0.7,  0.7,  1.2, 11. , 11.5,  5.8,  1.9,  1.9,
        4.5, 75. ,  3. , 22.8,  8.9,  1.7,  1.9, 14.1,  0.6,  0.6,  0.8,
        0.8, 14.8, 10.6,  8. ,  2.8,  2.9,  1.9,  0.6,  1.1,  1.5,  3.2,
        2.1,  1.9,  0.8,  6.3,  5.8,  2.3,  1.3,  2. ,  2.4,  2. ,  0.6,
        0.9, 27.2,  0.6,  0.6,  0.8,  1. ,  0.7,  2.5,  3.6,  3.9,  0.9,
        0.9,  0.8,  2.7,  2.7,  0.9,  1.7,  0.6,  0.9,  1.1,  0.6,  0.8,
        0.8,  0.9,  0.9,  1.1,  1.7,  0.6,  1.3,  0.7,  1. ,  0.6,  1.5,
        0.8,  2.7,  2. ,  0.9,  1.5,  0.8,  0.9,  0.9,  0.9,  0.7,  0.8,
        0.8,  0.9,  0.8,  0.9,  1.8,  0.9,  0.7,  1.2,  2.1,  0.9,  1.1,
        0.6,  0.7,  1.7,  0.9,  0.8,  0.8, 30.5, 16.4,  1.5,  0.8,  0.8,
        0.8,  0.9,  1.2,  0.9, 14.5,  0.6,  0.7,  0.8, 18.5,  0.7,  1.8,
        1.9,  0.9,  2. ,  2.2,  1. ,  0.8,  0.7,  0.7,  1.3,  0.9,  1.5,
        0.8,  1.3,  1. ,  4.5,  1. ,  0.7,  0.6,  1.1,  2.4,  0.6,  0.9,
        0.9,  1.1,  0.9,  0.8,  0.9,  1.7,  0.7,  0.8,  1.4,  1.6,  0.8,
        0.8,  1.1,  0.8, 23.2,  1.3,  0.8,  2. ,  0.9,  0.9,  0.7,  3.7,
        0.9,  0.7,  0.8,  1.7,  0.8,  2.6,  0.8,  1.2,  3.3,  0.8,  0.7,
        2. ,  1.7,  7.1,  0.7,  0.7,  0.7,  6.7,  2.5,  1.8,  1.4,  0.9,
        0.8,  0.8,  3.1,  0.8,  2.9,  0.6,  0.7,  1.3,  0.8,  1.8,  1.3,
        0.7,  1.4,  0.8,  1.4,  0.7,  2.1,  0.7,  0.8,  0.7,  0.7,  1.1,
        0.9,  0.8,  0.7,  0.7,  2.2,  0.8,  0.8, 22.6,  0.8,  0.7,  0.7,
        0.7,  3.5,  0.7,  0.6,  0.7,  0.7,  1.7,  0.6,  0.7,  1.4,  3.7,
        0.8,  2.7,  0.8,  0.8,  0.6,  0.8,  0.9,  7.5,  2.7,  1. ,  0.8,
        1. ,  1. ,  0.8,  1. ,  0.7,  7.3,  0.5,  0.7,  0.8,  0.8,  0.7,
        1. ,  2.4,  5. ,  1.4,  2.3,  4.9,  0.7,  1.4,  1.3,  0.6,  0.7,
        4.2,  8.2, 10.9,  1. ,  1.2,  1.6,  0.7,  0.4,  1.3,  0.9,  0.6,
        1.9,  0.7,  0.8,  0.7,  0.9,  0.7,  0.5,  1. ,  1.6,  0.8,  0.8,
        0.8,  2.3,  7.4,  0.7,  0.8,  0.9,  0.8, 23.3,  0.8,  0.9,  7.9,
        0.8,  0.9,  0.7,  0.6,  0.6,  0.7,  0.8,  6.8,  1.1,  2.2,  0.8,
        0.7,  0.8,  0.7,  0.6,  0.6,  1. ,  1. ,  0.8,  1.1,  0.6,  0.7,
        1. ,  2. ,  2.2,  0.9,  0.6,  7.1,  3.4,  0.5,  2.3,  1.1,  0.8,
        5. ,  6.7,  0.8,  0.7,  0.7,  0.8,  0.8,  1. ,  1. ,  0.7,  0.7,
        0.7,  1. ,  2.2,  1.8,  3.6,  2.7,  2.8,  0.8, 19.8, 30.5, 32.6,
       17.7,  0.9, 18.4, 20. ,  0.8,  2.2,  1. ,  0.9,  1. ,  3.9,  0.9,
        0.9,  2.9, 26.3,  1.8,  4.4,  0.8,  0.6,  0.8,  0.9,  9.4,  3.5,
        1.7,  3.3,  1.1, 30.8,  0.7,  1.4,  1.6, 19.6, 15.8,  0.8,  1.8,
        0.7,  0.8,  0.8,  0.7,  1.2,  5.5,  0.7, 20.2, 27.7, 11.1,  2.1,
        3.3,  1.2,  0.6, 10.2,  1.8,  0.8,  0.7,  2.9,  4. , 42.8, 15.2,
       16.6, 17.3,  1.4,  0.6, 22.5,  1. ,  2.7, 16.7,  7.7,  2.6,  1.1,
       15.6,  3.7, 12.1, 25. , 15. , 12.7,  0.5,  0.6,  0.8,  1.3,  1. ])

In [45]:
df.describe()

,Age,TB,DB,Alkphos,Sgpt,Sgot,TP,ALB,AG,LiverPatient
count,583.000000,583.000000,583.000000,583.000000,583.000000,583.000000,583.000000,583.000000,579.000000,583.000000
mean,44.746141,3.298799,1.486106,290.576329,80.713551,109.910806,6.483190,3.141852,0.947064,0.713551
std,16.189833,6.209522,2.808498,242.937989,182.620356,288.918529,1.085451,0.795519,0.319592,0.452490
min,4.000000,0.400000,0.100000,63.000000,10.000000,10.000000,2.700000,0.900000,0.300000,0.000000
25%,33.000000,0.800000,0.200000,175.500000,23.000000,25.000000,5.800000,2.600000,0.700000,0.000000
50%,45.000000,1.000000,0.300000,208.000000,35.000000,42.000000,6.600000,3.100000,0.930000,1.000000
75%,58.000000,2.600000,1.300000,298.000000,60.500000,87.000000,7.200000,3.800000,1.100000,1.000000
max,90.000000,75.000000,19.700000,2110.000000,2000.000000,4929.000000,9.600000,5.500000,2.800000,1.000000

# Data Preprocessing

In [46]:
df.isnull().sum()

Age             0
Gender          0
TB              0
DB              0
Alkphos         0
Sgpt            0
Sgot            0
TP              0
ALB             0
AG              4
LiverPatient    0
dtype: int64

In [47]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
578    False
579    False
580    False
581    False
582    False
Length: 583, dtype: bool

In [48]:
df.duplicated().sum()

13

In [51]:
df.drop_duplicates()

     Age  Gender    TB   DB  Alkphos  Sgpt  Sgot   TP  ALB    AG  LiverPatient
0     65  Female   0.7  0.1      187    16    18  6.8  3.3  0.90             1
1     62    Male  10.9  5.5      699    64   100  7.5  3.2  0.74             1
2     62    Male   7.3  4.1      490    60    68  7.0  3.3  0.89             1
3     58    Male   1.0  0.4      182    14    20  6.8  3.4  1.00             1
4     72    Male   3.9  2.0      195    27    59  7.3  2.4  0.40             1
..   ...     ...   ...  ...      ...   ...   ...  ...  ...   ...           ...
578   60    Male   0.5  0.1      500    20    34  5.9  1.6  0.37             0
579   40    Male   0.6  0.1       98    35    31  6.0  3.2  1.10             1
580   52    Male   0.8  0.2      245    48    49  6.4  3.2  1.00             1
581   31    Male   1.3  0.5      184    29    32  6.8  3.4  1.00             1
582   38    Male   1.0  0.3      216    21    24  7.3  4.4  1.50             0

[570 rows x 11 columns]

In [52]:
df.isnull().sum()

Age             0
Gender          0
TB              0
DB              0
Alkphos         0
Sgpt            0
Sgot            0
TP              0
ALB             0
AG              4
LiverPatient    0
dtype: int64

In [53]:
df.sort_values(by='TB',ascending=True)

,Age,Gender,TB,DB,Alkphos,Sgpt,Sgot,TP,ALB,AG,LiverPatient
425,58,Male,0.4,0.1,100,59,126,4.3,2.5,1.40,1
104,63,Male,0.5,0.1,170,21,28,5.5,2.5,0.80,1
578,60,Male,0.5,0.1,500,20,34,5.9,1.6,0.37,0
480,7,Male,0.5,0.1,352,28,51,7.9,4.2,1.10,0
402,42,Female,0.5,0.1,162,155,108,8.1,4.0,0.90,1
...,...,...,...,...,...,...,...,...,...,...,...
259,42,Male,30.5,14.2,285,65,130,5.2,2.1,0.60,1
531,40,Male,30.8,18.3,285,110,186,7.9,2.7,0.50,1
505,32,Male,32.6,14.1,219,95,235,5.8,3.1,1.10,1
559,26,Male,42.8,19.7,390,75,138,7.5,2.6,0.50,1
166,55,Male,75.0,3.6,332,40,66,6.2,2.5,0.60,1

In [55]:
df['Age'].mean()

44.74614065180103

In [56]:
df['Age'].median()

45.0

In [57]:
df['Age'].max()

90

In [58]:
df['Age'].min()

4

In [59]:
df['Age'].sum()

26087

In [60]:
df['Age'].mode()

0    60
Name: Age, dtype: int64